# 03 numpy.array基础

In [1]:
import numpy

In [2]:
numpy.__version__

'1.16.2'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.16.2'

## Python List 的特点

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L[5]

5

In [7]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [8]:
L[5] = "Machine Learning"

In [9]:
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

In [10]:
import array

In [11]:
arr = array.array('i', [i for i in range(10)])

In [12]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

## numpy.array

In [15]:
nparr = np.array([i for i in range(10)])

In [16]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
nparr[5]

5

In [18]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [19]:
nparr.dtype

dtype('int64')

## 其它创建numpy.array的方法

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros(10).dtype

dtype('float64')

In [22]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.zeros(10, dtype = int).dtype

dtype('int64')

In [24]:
np.zeros([3, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.zeros(shape = [3, 5], dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.full([3,5], 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [29]:
np.full(shape = [3,5], fill_value = 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

## arange

In [30]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [31]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linspace

In [34]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## random

In [35]:
np.random.randint(0, 10)

2

In [36]:
np.random.randint(0, 10, 10)

array([8, 6, 2, 0, 6, 2, 2, 8, 4, 2])

In [37]:
np.random.randint(4, 8, size = 10)

array([6, 6, 4, 5, 5, 5, 5, 5, 4, 7])

In [38]:
np.random.randint(4, 8, size = [3, 5])

array([[4, 5, 7, 4, 6],
       [5, 4, 6, 7, 5],
       [5, 6, 4, 7, 7]])

In [39]:
np.random.seed(666)
np.random.randint(4, 8, size = [3, 5])

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [40]:
np.random.seed(666)
np.random.randint(4, 8, size = [3, 5])

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [41]:
np.random.random()

0.2811684913927954

In [42]:
np.random.random(10)

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [43]:
np.random.random([3, 5])

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949],
       [0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981]])

In [44]:
np.random.normal()

0.7760516793129695

In [45]:
np.random.normal(10, 100)

128.06359754812632

In [46]:
np.random.normal(10, 100)

16.102403954600113

In [47]:
np.random.normal(0, 1, [3, 5])

array([[ 1.07856138, -0.79783572,  1.1701326 ,  0.1121217 ,  0.03185388],
       [-0.19206285,  0.78611284, -1.69046314, -0.98873907,  0.31398563],
       [ 0.39638567,  0.57656584, -0.07019407,  0.91250436,  1.00470497]])