# 05 numpy.array 中的运算

给定一个向量，让向量中每一个数乘以2

a = (0, 1, 2)

a * 2 = (0, 2, 4)

In [1]:
n = 10
L = [i for i in range(10)]

In [2]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
import numpy as np
L = np.arange(n)

In [4]:
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
L * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
L / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [7]:
L // 2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

In [8]:
L ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
L % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [10]:
1 / L

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [11]:
1 // L

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.abs(X)

NameError: name 'X' is not defined

In [13]:
np.abs(L)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.sin(L)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [15]:
np.cos(L)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [16]:
np.tan(L)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [17]:
np.exp(X)

NameError: name 'X' is not defined

In [18]:
np.exp(L)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [19]:
np.power(3, L)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683])

In [20]:
np.log(10)

2.302585092994046

In [21]:
np.log(exp(2))

NameError: name 'exp' is not defined

In [22]:
np.log(np.exp(2))

2.0

In [23]:
np.log(L)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [24]:
np.log2(L)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [25]:
np.log10(L)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

### 矩阵运算

In [26]:
A = np.arange(4).reshape(2, 2)

In [27]:
A

array([[0, 1],
       [2, 3]])

In [28]:
B = np.full((2, 2), 10)

In [29]:
B

array([[10, 10],
       [10, 10]])

In [30]:
A + B

array([[10, 11],
       [12, 13]])

In [31]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [32]:
A * B

array([[ 0, 10],
       [20, 30]])

In [33]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [34]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [35]:
A

array([[0, 1],
       [2, 3]])

In [36]:
A.T

array([[0, 2],
       [1, 3]])

### 向量和矩阵的运算

In [37]:
v = np.array([1, 2])

In [38]:
A

array([[0, 1],
       [2, 3]])

In [39]:
v + A

array([[1, 3],
       [3, 5]])

In [40]:
A.shape

(2, 2)

In [41]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [42]:
np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [43]:
np.tile(v, (2, 1))

array([[1, 2],
       [1, 2]])

In [44]:
v.dot(A)

array([4, 7])

In [45]:
A.dot(v)

array([2, 8])

### 矩阵的逆

In [46]:
A

array([[0, 1],
       [2, 3]])

In [47]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [48]:
invA = np.linalg.inv(A)

In [49]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [50]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])