# 06 numpy中的聚合操作

In [1]:
import numpy as np

L = np.random.random(100)

In [2]:
L

array([0.6535067 , 0.83776142, 0.53106407, 0.52887023, 0.06601745,
       0.07253529, 0.73543975, 0.46334334, 0.40359903, 0.35929441,
       0.22517071, 0.21385238, 0.3981769 , 0.67614233, 0.11388083,
       0.95068199, 0.08525854, 0.44985874, 0.80400185, 0.86122747,
       0.20626435, 0.56227268, 0.36540766, 0.94227478, 0.20113105,
       0.40017222, 0.22046949, 0.90658849, 0.42289758, 0.69828332,
       0.81275709, 0.967663  , 0.98771257, 0.4123813 , 0.04933121,
       0.68852216, 0.3326167 , 0.68035294, 0.08225436, 0.64626158,
       0.51338823, 0.46426768, 0.71877302, 0.54715915, 0.93530193,
       0.907351  , 0.8657532 , 0.72926963, 0.74314196, 0.26519239,
       0.50861105, 0.85635433, 0.70094666, 0.37764113, 0.2474888 ,
       0.75781629, 0.75234402, 0.01456655, 0.98663905, 0.02184229,
       0.89300322, 0.36300888, 0.60412336, 0.71356377, 0.52811088,
       0.63090614, 0.53098538, 0.73842102, 0.28184016, 0.10821851,
       0.81546559, 0.90479303, 0.81110025, 0.5167216 , 0.47778

In [3]:
sum(L)

55.16025068737966

In [4]:
np.sum(L)

55.160250687379644

In [5]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

156 ms ± 4.69 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
639 µs ± 25.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
np.min(big_array)

3.1139894007825575e-06

In [7]:
np.max(big_array)

0.9999998743367576

In [8]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
np.sum(X)

120

In [10]:
np.sum(X, axis = 0)

array([24, 28, 32, 36])

In [11]:
np.sum(X, axis = 1)

array([ 6, 22, 38, 54])

In [12]:
np.prod(X)

0

In [13]:
np.prod(X + 1)

20922789888000

In [14]:
np.mean(X)

7.5

In [15]:
np.median(X)

7.5

In [16]:
np.percentile(big_array, q = 50)

0.5002332839291588

In [17]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q = percent))

3.1139894007825575e-06
0.2505461572260319
0.5002332839291588
0.7509437956887173
0.9999998743367576


In [18]:
np.var(big_array)

0.0834081504253871

In [19]:
np.std(big_array)

0.2888046925266054

In [20]:
np.std(big_array)**2

0.08340815042538709

In [21]:
x = np.random.normal(0, 1, size = 1000000)

In [22]:
np.mean(x)

0.0009580047021568363

In [23]:
np.std(x)

1.0000263006104535

In [24]:
np.var(x)

1.000052601912629

## 索引

In [25]:
np.min(x)

-5.220927678020471

In [26]:
np.argmin(x)

243503

In [27]:
x[243503]

-5.220927678020471

## 排序和使用索引

In [28]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
np.random.shuffle(x)
x

array([ 7,  1, 15, 10, 13, 11,  4,  3,  2, 12,  5, 14,  8,  9,  6,  0])

In [30]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
x

array([ 7,  1, 15, 10, 13, 11,  4,  3,  2, 12,  5, 14,  8,  9,  6,  0])

In [32]:
x.sort()

In [33]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
X = np.random.randint(10, size=(4, 4))

In [35]:
X

array([[5, 5, 7, 2],
       [8, 0, 5, 6],
       [6, 4, 1, 2],
       [5, 1, 2, 8]])

In [36]:
np.sort(X)

array([[2, 5, 5, 7],
       [0, 5, 6, 8],
       [1, 2, 4, 6],
       [1, 2, 5, 8]])

In [37]:
np.sort(X, axis = 1)

array([[2, 5, 5, 7],
       [0, 5, 6, 8],
       [1, 2, 4, 6],
       [1, 2, 5, 8]])

In [38]:
np.sort(X, axis = 0)

array([[5, 0, 1, 2],
       [5, 1, 2, 2],
       [6, 4, 5, 6],
       [8, 5, 7, 8]])

In [39]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
np.random.shuffle(x)
x

array([ 1,  2,  6,  9,  5, 11,  7, 13,  0, 14,  3,  4, 15,  8, 10, 12])

In [41]:
np.argsort(x)

array([ 8,  0,  1, 10, 11,  4,  2,  6, 13,  3, 14,  5, 15,  7,  9, 12])

In [42]:
np.partition(x, 3)

array([ 1,  0,  2,  3,  4,  5,  7,  6,  8, 10,  9, 11, 12, 15, 14, 13])

In [43]:
np.argpartition(x, 3)

array([ 0,  8,  1, 10, 11,  4,  6,  2, 13, 14,  3,  5, 15, 12,  9,  7])

In [44]:
X

array([[5, 5, 7, 2],
       [8, 0, 5, 6],
       [6, 4, 1, 2],
       [5, 1, 2, 8]])

In [45]:
np.argsort(X, axis = 1)

array([[3, 0, 1, 2],
       [1, 2, 3, 0],
       [2, 3, 1, 0],
       [1, 2, 0, 3]])