# Fancy Indexing

In [1]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [3]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [4]:
x{3:9:2}

SyntaxError: invalid syntax (<ipython-input-4-43110b70035d>, line 1)

In [5]:
x[3:9:2]

array([3, 5, 7])

In [6]:
ind = [3, 5, 8]

In [7]:
x[ind]

array([3, 5, 8])

In [8]:
ind = np.array([0, 2],
                    [1, 3])
x[ind]

TypeError: data type not understood

In [9]:
ind = np.array([[0, 2],
                     [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [10]:
X = x.reshape(4,-1)

In [11]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [13]:
col = [True, False, True, True]

In [14]:
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

## numpy.array 的比较

In [15]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [17]:
np.any(x == 0)

True

In [18]:
np.any(x < 0)

False

In [19]:
np.any(x >= 0)

True

In [20]:
np.all(x >= 0)

True

In [21]:
np.all(x > 0)

False

In [22]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
np.sum(X%2==0)

8