# 12 测试算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
X = iris.data
Y = iris.target

In [5]:
X.shape

(150, 4)

In [6]:
Y.shape

(150,)

## train_test_split

In [7]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
shuffle_indexs = np.random.permutation(len(X))

In [9]:
shuffle_indexs

array([ 17,  88, 145,  84,  59,  20,  53,  99,  28,  33, 109,  50,  81,
         1, 140, 130,  73,  18,  43,  16, 149,  64, 146, 134,  44,  25,
        31,  22,  48,  52,  26,  34, 121,   3, 112,  96,  87,  58,  76,
       138, 115, 123,  40, 116,  91,  82,  38,  69,  30, 142,  79,  36,
        29,  75, 124,  60,  54, 136,  11,  65,  39, 113,  66, 119,  47,
       111,  21,  83,   2,  72,  19, 106,  80, 132,  41,  15, 144,  51,
        85,  94,  14, 131,  46, 117, 133,  77,  90,  95, 107, 104, 105,
         8,  13,  57,   6,   5,  63,  67,  56, 147, 148,  10, 108,  27,
       137,  68,  37,  23, 102,  89,   4,  49,  62, 127, 100, 128, 125,
        70, 141,  98, 118, 129, 110, 139,   9, 143, 120,  35,  45,  32,
         0,  92, 122, 126, 101,  93,  55,  61,  74,  71,  24,  86,  97,
       135,  78,  42, 114,  12,   7, 103])

In [10]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [11]:
test_size

30

In [12]:
test_indexs = shuffle_indexs[:test_size]
train_indexs = shuffle_indexs[test_size:]

In [13]:
X_train = X[train_indexs]
Y_train = Y[train_indexs]

X_test = X[test_indexs]
Y_test = Y[test_indexs]

## 使用算法

In [14]:
from kNN_function.model_selection import train_test_split

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)

TypeError: cannot unpack non-iterable NoneType object

In [22]:
x_train, x_test, y_train, y_test = train_test_split(X, Y)

TypeError: cannot unpack non-iterable NoneType object

In [19]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [20]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [28]:
train_test_split(X, Y)

In [29]:
x = train_test_split(X, Y)


In [30]:
x

In [31]:
x

In [32]:
x

In [36]:
train_test_split(X, Y)

In [37]:
train_test_split?

In [38]:
X.shape

(150, 4)

In [39]:
Y.shape

(150,)

In [40]:
train_test_split(X, Y)

In [1]:
from kNN_function.model_selection import free

In [2]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)

NameError: name 'train_test_split' is not defined

In [3]:
from kNN_function.model_selection import train_test_split

In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)

NameError: name 'X' is not defined

In [5]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [6]:
iris = datasets.load_iris()

In [7]:
X = iris.data
Y = iris.target

In [8]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)

start
[[5.7 2.5 5.  2. ]
 [4.9 3.  1.4 0.2]
 [5.7 2.6 3.5 1. ]
 [6.4 3.2 5.3 2.3]
 [5.2 3.5 1.5 0.2]
 [5.1 2.5 3.  1.1]
 [6.8 3.2 5.9 2.3]
 [6.4 3.2 4.5 1.5]
 [6.2 3.4 5.4 2.3]
 [4.7 3.2 1.3 0.2]
 [5.1 3.5 1.4 0.2]
 [6.5 3.2 5.1 2. ]
 [5.5 2.4 3.7 1. ]
 [5.8 2.6 4.  1.2]
 [5.5 2.3 4.  1.3]
 [5.1 3.5 1.4 0.3]
 [5.4 3.4 1.5 0.4]
 [5.2 2.7 3.9 1.4]
 [5.7 2.9 4.2 1.3]
 [6.3 2.3 4.4 1.3]
 [6.6 3.  4.4 1.4]
 [6.  3.  4.8 1.8]
 [5.4 3.9 1.7 0.4]
 [7.4 2.8 6.1 1.9]
 [5.8 2.7 3.9 1.2]
 [5.1 3.8 1.5 0.3]
 [6.7 3.  5.2 2.3]
 [6.1 2.8 4.7 1.2]
 [6.6 2.9 4.6 1.3]
 [5.9 3.  4.2 1.5]
 [5.5 2.6 4.4 1.2]
 [6.9 3.1 4.9 1.5]
 [6.7 3.1 4.7 1.5]
 [7.7 3.8 6.7 2.2]
 [4.4 2.9 1.4 0.2]
 [6.3 2.7 4.9 1.8]
 [5.1 3.4 1.5 0.2]
 [5.7 3.  4.2 1.2]
 [6.5 3.  5.8 2.2]
 [5.7 3.8 1.7 0.3]
 [5.8 4.  1.2 0.2]
 [5.2 3.4 1.4 0.2]
 [6.3 3.3 6.  2.5]
 [7.2 3.6 6.1 2.5]
 [5.6 2.9 3.6 1.3]
 [6.4 3.1 5.5 1.8]
 [5.1 3.7 1.5 0.4]
 [6.3 2.5 4.9 1.5]
 [6.  2.2 4.  1. ]
 [5.4 3.  4.5 1.5]
 [5.  3.  1.6 0.2]
 [5.5 3.5 1.3 0.2]
 [6.9 

TypeError: cannot unpack non-iterable NoneType object

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)

start
[[6.7 3.1 4.7 1.5]
 [5.2 3.5 1.5 0.2]
 [6.9 3.1 5.4 2.1]
 [6.6 3.  4.4 1.4]
 [6.4 3.2 5.3 2.3]
 [6.2 3.4 5.4 2.3]
 [5.5 2.4 3.7 1. ]
 [7.4 2.8 6.1 1.9]
 [7.2 3.2 6.  1.8]
 [6.4 2.7 5.3 1.9]
 [6.3 2.9 5.6 1.8]
 [5.5 3.5 1.3 0.2]
 [5.5 2.4 3.8 1.1]
 [5.2 4.1 1.5 0.1]
 [5.5 2.3 4.  1.3]
 [5.9 3.2 4.8 1.8]
 [4.8 3.4 1.9 0.2]
 [5.8 2.7 5.1 1.9]
 [4.8 3.1 1.6 0.2]
 [5.8 4.  1.2 0.2]
 [6.6 2.9 4.6 1.3]
 [6.4 3.1 5.5 1.8]
 [6.7 3.  5.2 2.3]
 [4.6 3.2 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [6.5 3.  5.2 2. ]
 [4.9 3.1 1.5 0.1]
 [5.  3.5 1.6 0.6]
 [6.5 3.  5.5 1.8]
 [6.8 3.2 5.9 2.3]
 [5.6 2.9 3.6 1.3]
 [5.  3.4 1.5 0.2]
 [6.2 2.2 4.5 1.5]
 [6.7 3.  5.  1.7]
 [5.1 3.7 1.5 0.4]
 [5.1 3.3 1.7 0.5]
 [5.7 2.8 4.1 1.3]
 [4.6 3.4 1.4 0.3]
 [7.2 3.6 6.1 2.5]
 [6.1 3.  4.6 1.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [6.  2.9 4.5 1.5]
 [6.3 2.5 5.  1.9]
 [5.1 3.5 1.4 0.2]
 [6.1 2.9 4.7 1.4]
 [5.  3.  1.6 0.2]
 [6.  2.2 4.  1. ]
 [5.  3.4 1.6 0.4]
 [4.9 3.  1.4 0.2]
 [6.5 3.  5.8 2.2]
 [4.4 

TypeError: cannot unpack non-iterable NoneType object

In [10]:
from kNN_function.model_selection import train_test_split 

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)

start
[[6.2 3.4 5.4 2.3]
 [5.8 2.7 4.1 1. ]
 [5.7 2.8 4.5 1.3]
 [6.8 3.2 5.9 2.3]
 [5.4 3.4 1.5 0.4]
 [6.9 3.1 4.9 1.5]
 [4.6 3.4 1.4 0.3]
 [4.9 3.  1.4 0.2]
 [5.  2.3 3.3 1. ]
 [5.5 2.6 4.4 1.2]
 [6.3 2.9 5.6 1.8]
 [5.4 3.4 1.7 0.2]
 [5.5 2.3 4.  1.3]
 [6.4 3.1 5.5 1.8]
 [5.5 4.2 1.4 0.2]
 [6.4 3.2 4.5 1.5]
 [6.7 2.5 5.8 1.8]
 [5.1 3.3 1.7 0.5]
 [4.9 3.6 1.4 0.1]
 [6.3 2.5 5.  1.9]
 [5.2 4.1 1.5 0.1]
 [4.6 3.1 1.5 0.2]
 [6.4 2.8 5.6 2.1]
 [5.  2.  3.5 1. ]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [6.7 3.3 5.7 2.1]
 [4.8 3.  1.4 0.3]
 [5.  3.2 1.2 0.2]
 [5.5 2.4 3.7 1. ]
 [5.7 2.5 5.  2. ]
 [6.1 3.  4.9 1.8]
 [5.1 3.5 1.4 0.3]
 [6.5 3.  5.8 2.2]
 [5.6 3.  4.5 1.5]
 [6.1 2.6 5.6 1.4]
 [5.5 2.4 3.8 1.1]
 [6.7 3.  5.  1.7]
 [5.  3.5 1.6 0.6]
 [5.6 2.7 4.2 1.3]
 [4.8 3.  1.4 0.1]
 [6.9 3.1 5.4 2.1]
 [6.3 2.3 4.4 1.3]
 [5.7 2.6 3.5 1. ]
 [5.8 2.7 3.9 1.2]
 [6.8 3.  5.5 2.1]
 [5.8 2.7 5.1 1.9]
 [5.9 3.  4.2 1.5]
 [5.1 3.8 1.6 0.2]
 [6.1 2.9 4.7 1.4]
 [6.7 3.  5.2 2.3]
 [5.7 3.8 1.7 0.3]
 [5.2 

TypeError: cannot unpack non-iterable NoneType object