# 数据归一化处理

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## 最值归一化 Normalization

In [2]:
x = np.random.randint(0, 100, size=100)

In [3]:
x

array([45, 27, 70, 66, 48, 40, 16, 95, 56, 40, 41, 42, 86, 85, 71, 80, 54,
       32, 22, 33, 93,  6, 36, 19, 83, 42, 46, 56, 44, 22, 59, 63,  1, 15,
       45, 78, 14, 40, 17, 92, 32, 89, 35,  8, 48, 27, 44, 63, 34, 11, 63,
       71, 38, 77, 62, 49, 49, 19, 99, 34, 95, 94, 55, 40, 61, 67, 12, 48,
       86, 44, 52, 14, 34, 81, 58, 55, 23, 77, 13,  5, 90, 53, 24, 65, 78,
       69, 52, 43, 85, 25, 27, 69, 45, 51, 19, 20,  0, 39, 33, 34])

In [4]:
(x - np.min(x)) / (np.max(x) - np.min(x))

array([0.45454545, 0.27272727, 0.70707071, 0.66666667, 0.48484848,
       0.4040404 , 0.16161616, 0.95959596, 0.56565657, 0.4040404 ,
       0.41414141, 0.42424242, 0.86868687, 0.85858586, 0.71717172,
       0.80808081, 0.54545455, 0.32323232, 0.22222222, 0.33333333,
       0.93939394, 0.06060606, 0.36363636, 0.19191919, 0.83838384,
       0.42424242, 0.46464646, 0.56565657, 0.44444444, 0.22222222,
       0.5959596 , 0.63636364, 0.01010101, 0.15151515, 0.45454545,
       0.78787879, 0.14141414, 0.4040404 , 0.17171717, 0.92929293,
       0.32323232, 0.8989899 , 0.35353535, 0.08080808, 0.48484848,
       0.27272727, 0.44444444, 0.63636364, 0.34343434, 0.11111111,
       0.63636364, 0.71717172, 0.38383838, 0.77777778, 0.62626263,
       0.49494949, 0.49494949, 0.19191919, 1.        , 0.34343434,
       0.95959596, 0.94949495, 0.55555556, 0.4040404 , 0.61616162,
       0.67676768, 0.12121212, 0.48484848, 0.86868687, 0.44444444,
       0.52525253, 0.14141414, 0.34343434, 0.81818182, 0.58585

In [5]:
X = np.random.randint(0,100,size=(50,2))

In [6]:
X[:10,:]

array([[70, 97],
       [11, 86],
       [98, 56],
       [16, 12],
       [86,  3],
       [43, 50],
       [73, 61],
       [47, 36],
       [14, 83],
       [24, 12]])

In [7]:
X = np.array(X, dtype=float)

In [8]:
X[:10,:]

array([[70., 97.],
       [11., 86.],
       [98., 56.],
       [16., 12.],
       [86.,  3.],
       [43., 50.],
       [73., 61.],
       [47., 36.],
       [14., 83.],
       [24., 12.]])

In [9]:
X[:,0] = (X[:,0] - np.min(X[:,0])) / (np.max(X[:,0]) - np.min(X[:,0]))

In [10]:
X[:,1] = (X[:,1] - np.min(X[:,1])) / (np.max(X[:,1]) - np.min(X[:,1]))

In [11]:
X[:10,:]

array([[0.71428571, 0.97959184],
       [0.1122449 , 0.86734694],
       [1.        , 0.56122449],
       [0.16326531, 0.1122449 ],
       [0.87755102, 0.02040816],
       [0.43877551, 0.5       ],
       [0.74489796, 0.6122449 ],
       [0.47959184, 0.35714286],
       [0.14285714, 0.83673469],
       [0.24489796, 0.1122449 ]])

In [12]:
plt.scatter(X[:,0],X[:,1])
plt.show()

In [13]:
np.mean(X[:,0])

0.4810204081632653

In [14]:
np.std(X[:,0])

0.3104524381739978

## 均值方差归一化 Standardization

In [15]:
X2 = np.random.randint(0, 100, (50,2))

In [16]:
X2 = np.array(X2, dtype=float)

In [17]:
X2[:,0] = (X2[:,0] - np.mean(X2[:,0])) / np.std(X2[:,0])

In [18]:
X2[:,1] = (X2[:,1] - np.mean(X2[:,1])) / np.std(X2[:,1])

In [19]:
plt.scatter(X2[:,0],X2[:,1])
plt.show()

In [20]:
np.mean(X2[:,0])

-3.1086244689504386e-17

In [21]:
np.std(X2[:,0])

1.0