# 19 实现多元线性回归模型

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
boston = datasets.load_boston()

X = boston.data
y = boston.target

X = X[y < 50.0]
y = y[y < 50.0]

In [3]:
X.shape

(490, 13)

In [4]:
from kNN_function.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, seed=666)

In [5]:
from kNN_function.LinearRegression import LinearRegression

In [6]:
reg = LinearRegression()
reg.fit_normal(X_train, y_train)

LinearRegression()

In [7]:
reg.coef_

array([-1.20354261e-01,  3.64423279e-02, -3.61493155e-02,  5.12978140e-02,
       -1.15775825e+01,  3.42740062e+00, -2.32311760e-02, -1.19487594e+00,
        2.60101728e-01, -1.40219119e-02, -8.35430488e-01,  7.80472852e-03,
       -3.80923751e-01])

In [8]:
reg.intercept_

34.117399723224324

In [9]:
reg.score(X_test, y_test)

0.8129794056212793

### (后来进来写的)梯度下降法实现

In [10]:
lin_reg2 = LinearRegression()
lin_reg2.fit_gd(X_train, y_train)

/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/Users/mac/Desktop/丁凯星敲代码/MachineLearning/kNN_function/LinearRegression.py:32: RuntimeWarning: overflow encountered in square
  return np.sum((y - X_b.dot(theta)) ** 2) / len(y)
/Users/mac/Desktop/丁凯星敲代码/MachineLearning/kNN_function/LinearRegression.py:53: RuntimeWarning: invalid value encountered in double_scalars
  if (abs(J(theta, X_b, y) - J(last_theta, X_b, y)) < epsilon):


LinearRegression()

In [11]:
lin_reg2.coef_

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [12]:
lin_reg2.fit_gd(X_train, y_train, eta=0.000001)

LinearRegression()

In [13]:
lin_reg2.coef_

array([-0.10245704,  0.11535876, -0.06248791,  0.00207516,  0.00447152,
        0.11954208,  0.04684195,  0.03460927, -0.00452122,  0.00324507,
        0.1271939 ,  0.04484862, -0.22542441])

In [14]:
lin_reg2.score(X_test, y_test)

0.27586818724477224

In [15]:
%time lin_reg2.fit_gd(X_train, y_train, eta=0.000001, n_iters=1e6)

CPU times: user 3min 11s, sys: 1.09 s, total: 3min 12s
Wall time: 1min 36s


LinearRegression()

In [16]:
lin_reg2.score(X_test, y_test)

0.7542932581943915

### 使用梯度下降法前进行数据归一化

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
standardScaler = StandardScaler()
standardScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [20]:
X_train_standard = standardScaler.transform(X_train)

In [21]:
lin_reg3 = LinearRegression()
%time lin_reg3.fit_gd(X_train_standard, y_train)

CPU times: user 1.06 s, sys: 32 ms, total: 1.09 s
Wall time: 605 ms


LinearRegression()

In [22]:
X_test_standard = standardScaler.transform(X_test)

In [23]:
lin_reg3.score(X_test_standard, y_test)

0.8129873310487505